version: '3.7'
services:
  fe:
    image: node:12-alpine
    volumes:
      - ../../fe:/app
    working_dir: /app
    command: yarn run dev
    ports:
      - 3000:3000
 
  be:
    image: node:12-alpine
    volumes:
      - ../../be:/app
    working_dir: /app
    command: yarn run dev
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./mysql/config:/etc/mysql/conf.d/my.cnf
    command: mysqld --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
volumes:
  mysql_data:
    driver: local